// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.

using System.Collections.Immutable;
using System.Reflection;

using FluentAssertions;

using KubeOps.Generator.Generators;
using KubeOps.Generator.Test.Entities;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace KubeOps.Generator.Test;

public sealed partial class ControllerRegistrationGeneratorTest
{
    [Theory]
    [InlineData(
        """
                using KubeOps.Abstractions.Reconciliation.Controller;
                
                public class V1TestEntityController : IEntityController<V1TestEntityFromReferencedAssemblyInGlobalNamespace>
                {
                }
                """,
        """
                     // <auto-generated>
                     // This code was generated by a tool.
                     // Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
                     // </auto-generated>
                     #pragma warning disable CS1591
                     using KubeOps.Abstractions.Builder;

                     public static class ControllerRegistrations
                     {
                         public static IOperatorBuilder RegisterControllers(this IOperatorBuilder builder)
                         {
                             builder.AddController<global::V1TestEntityController, global::V1TestEntityFromReferencedAssemblyInGlobalNamespace>();
                             return builder;
                         }
                     }
                     """,
        TestDisplayName = "Test controller with entity from referenced assembly in global namespace")]
    [InlineData(
        """
                using k8s;
                using k8s.Models;
                using KubeOps.Abstractions.Reconciliation.Controller;

                public abstract class EntityControllerBase<TEntity> : IEntityController<TEntity>
                    where TEntity : IKubernetesObject<V1ObjectMeta>
                {
                }
                
                public sealed class V1TestEntityController : EntityControllerBase<V1TestEntityFromReferencedAssemblyInGlobalNamespace>
                {
                }
                """,
        """
                     // <auto-generated>
                     // This code was generated by a tool.
                     // Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
                     // </auto-generated>
                     #pragma warning disable CS1591
                     using KubeOps.Abstractions.Builder;

                     public static class ControllerRegistrations
                     {
                         public static IOperatorBuilder RegisterControllers(this IOperatorBuilder builder)
                         {
                             builder.AddController<global::V1TestEntityController, global::V1TestEntityFromReferencedAssemblyInGlobalNamespace>();
                             return builder;
                         }
                     }
                     """,
        TestDisplayName = "Test controller with inheritance and entity from referenced assembly in global namespace.")]
    [InlineData(
        """
                using k8s;
                using k8s.Models;
                using KubeOps.Abstractions.Reconciliation.Controller;

                public partial class V1TestEntityController : IEntityController<V1TestEntityFromReferencedAssemblyInGlobalNamespace>
                {
                }

                public partial class V1TestEntityController
                {
                }
                """,
        """
                     // <auto-generated>
                     // This code was generated by a tool.
                     // Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
                     // </auto-generated>
                     #pragma warning disable CS1591
                     using KubeOps.Abstractions.Builder;

                     public static class ControllerRegistrations
                     {
                         public static IOperatorBuilder RegisterControllers(this IOperatorBuilder builder)
                         {
                             builder.AddController<global::V1TestEntityController, global::V1TestEntityFromReferencedAssemblyInGlobalNamespace>();
                             return builder;
                         }
                     }
                     """,
        TestDisplayName = "Test entity controller from referenced assembly in global namespace with partial controller")]
    [InlineData(
        """
        using k8s;
        using k8s.Models;
        using KubeOps.Generator.Test.Entities;
        using KubeOps.Abstractions.Reconciliation.Controller;

        [KubernetesEntity(Group = "testing.dev", ApiVersion = "v1", Kind = "TestEntity")]
        public class V1TestEntity : IKubernetesObject<V1ObjectMeta>
        {
        }
        
        public sealed class V1TestEntityController : IEntityController<KubeOps.Generator.Test.Entities.V1TestEntity>
        {
        }

        public sealed class V1TestEntityController2 : IEntityController<V1TestEntity>
        {
        }
        """,
        """
        // <auto-generated>
        // This code was generated by a tool.
        // Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
        // </auto-generated>
        #pragma warning disable CS1591
        using KubeOps.Abstractions.Builder;

        public static class ControllerRegistrations
        {
            public static IOperatorBuilder RegisterControllers(this IOperatorBuilder builder)
            {
                builder.AddController<global::V1TestEntityController, global::KubeOps.Generator.Test.Entities.V1TestEntity>();
                builder.AddController<global::V1TestEntityController2, global::V1TestEntity>();
                return builder;
            }
        }
        """,
        TestDisplayName = "Test entity controller with referenced assembly and local entity with same name")]
    public void Should_Generate_Correct_Code_WithEntityFromReferencedAssembly(string input, string expectedResult)
    {
        var inputCompilation = input.CreateCompilation(
            additionalReferences: MetadataReference
                .CreateFromFile(typeof(V1TestEntityFromReferencedAssembly)
                .GetTypeInfo().Assembly.Location));
        expectedResult = expectedResult.ReplaceLineEndings();

        var driver = CSharpGeneratorDriver.Create(new ControllerRegistrationGenerator());
        driver.RunGeneratorsAndUpdateCompilation(
            inputCompilation,
            out var output,
            out ImmutableArray<Diagnostic> _,
            TestContext.Current.CancellationToken);

        var result = output.SyntaxTrees
            .First(s => s.FilePath.Contains("ControllerRegistrations.g.cs"))
            .ToString().ReplaceLineEndings();
        result.Should().Be(expectedResult);
    }
}
