// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.

using System.Collections.Immutable;
using System.Reflection;

using FluentAssertions;

using KubeOps.Generator.Generators;
using KubeOps.Generator.Test.Entities;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace KubeOps.Generator.Test;

public sealed partial class EntityDefinitionGeneratorTest
{
    [Theory]
    [InlineData(
        """
        using k8s;
        using k8s.Models;
        using KubeOps.Generator.Test.Entities;
        using KubeOps.Abstractions.Reconciliation.Controller;

        public sealed class V1TestEntityController : IEntityController<V1TestEntityFromReferencedAssemblyWithConstantValues>
        {
        }
        """,
        """
        // <auto-generated>
        // This code was generated by a tool.
        // Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
        // </auto-generated>
        #pragma warning disable CS1591
        using KubeOps.Abstractions.Builder;
        using KubeOps.Abstractions.Entities;

        public static class EntityDefinitions
        {
            public static readonly EntityMetadata V1TestEntityFromReferencedAssemblyWithConstantValues = new("TestEntity", "v1", "testing.dev", null);
        }
        """,
        TestDisplayName = "Test single entity (with controller as entity resolver reference)")]
    [InlineData(
        """
                using k8s;
                using k8s.Models;
                using KubeOps.Generator.Test.Entities;
                using KubeOps.Abstractions.Reconciliation.Controller;
                using KubeOps.Abstractions.Reconciliation.Finalizer;

                public sealed class V1TestEntityController : IEntityController<V1TestEntityFromReferencedAssemblyWithConstantValues>
                {
                }
                
                public sealed class V1TestEntityFinalizer : IEntityFinalizer<V1TestEntityFromReferencedAssemblyWithConstantValues>
                {
                }
        """,
        """
        // <auto-generated>
        // This code was generated by a tool.
        // Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
        // </auto-generated>
        #pragma warning disable CS1591
        using KubeOps.Abstractions.Builder;
        using KubeOps.Abstractions.Entities;

        public static class EntityDefinitions
        {
            public static readonly EntityMetadata V1TestEntityFromReferencedAssemblyWithConstantValues = new("TestEntity", "v1", "testing.dev", null);
        }
        """,
        TestDisplayName = "Test single entity (with controller and finalizer as entity resolver reference)")]
    [InlineData(
        """
        using k8s;
        using k8s.Models;
        using KubeOps.Generator.Test.Entities;
        using KubeOps.Abstractions.Reconciliation.Controller;
        using KubeOps.Abstractions.Reconciliation.Finalizer;

        public sealed class V1TestEntityController : IEntityController<V1TestEntityFromReferencedAssemblyWithConstantValues>
        {
        }

        public sealed class V1TestEntityFinalizer : IEntityFinalizer<V1TestEntityFromReferencedAssemblyInGlobalNamespace>
        {
        }
        """,
        """
        // <auto-generated>
        // This code was generated by a tool.
        // Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
        // </auto-generated>
        #pragma warning disable CS1591
        using KubeOps.Abstractions.Builder;
        using KubeOps.Abstractions.Entities;

        public static class EntityDefinitions
        {
            public static readonly EntityMetadata V1TestEntityFromReferencedAssemblyWithConstantValues = new("TestEntity", "v1", "testing.dev", null);
            public static readonly EntityMetadata V1TestEntityFromReferencedAssemblyInGlobalNamespace = new("TestEntity", "v1", "testing.dev", null);
        }
        """,
        TestDisplayName = "Test multiple entities (with controller and finalizer as entity resolver reference)")]
    public void Should_Generate_Correct_Code_WithEntityFromReferencedAssembly(string input, string expectedResult)
    {
        var inputCompilation = input.CreateCompilation(
            additionalReferences: MetadataReference
                .CreateFromFile(typeof(V1TestEntityFromReferencedAssembly)
                    .GetTypeInfo().Assembly.Location));
        expectedResult = expectedResult.ReplaceLineEndings();

        var driver = CSharpGeneratorDriver.Create(new EntityDefinitionGenerator());
        driver.RunGeneratorsAndUpdateCompilation(
            inputCompilation,
            out var output,
            out ImmutableArray<Diagnostic> _,
            TestContext.Current.CancellationToken);

        var result = output.SyntaxTrees
            .First(s => s.FilePath.Contains("EntityDefinitions.g.cs"))
            .ToString().ReplaceLineEndings();
        result.Should().Be(expectedResult);
    }
}
