// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.

using System.Collections.Immutable;
using System.Reflection;

using FluentAssertions;

using KubeOps.Generator.Generators;
using KubeOps.Generator.Test.Entities;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace KubeOps.Generator.Test;

public sealed partial class FinalizerRegistrationGeneratorTest
{
    [Theory]
    [InlineData(
        """
                using KubeOps.Generator.Test.Entities;
                using KubeOps.Abstractions.Reconciliation.Finalizer;

                public sealed class V1TestEntityFinalizer : IEntityFinalizer<V1TestEntityFromReferencedAssemblyWithConstantValues>
                {
                }
                """,
        """
                     // <auto-generated>
                     // This code was generated by a tool.
                     // Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
                     // </auto-generated>
                     #pragma warning disable CS1591
                     using KubeOps.Abstractions.Builder;

                     public static class FinalizerRegistrations
                     {
                         public const string V1TestEntityFinalizerIdentifier = "testing.dev/v1testentityfinalizer";
                         public static IOperatorBuilder RegisterFinalizers(this IOperatorBuilder builder)
                         {
                             builder.AddFinalizer<global::V1TestEntityFinalizer, global::KubeOps.Generator.Test.Entities.V1TestEntityFromReferencedAssemblyWithConstantValues>(V1TestEntityFinalizerIdentifier);
                             return builder;
                         }
                     }
                     """,
        TestDisplayName = "Test finalizer with entity from referenced assembly and constant values")]
    [InlineData(
        """
                using KubeOps.Generator.Test.Entities;
                using KubeOps.Abstractions.Reconciliation.Finalizer;
                
                public sealed class V1TestEntityFinalizer : IEntityFinalizer<V1TestEntityFromReferencedAssemblyInGlobalNamespace>
                {
                }
                """,
        """
                     // <auto-generated>
                     // This code was generated by a tool.
                     // Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
                     // </auto-generated>
                     #pragma warning disable CS1591
                     using KubeOps.Abstractions.Builder;

                     public static class FinalizerRegistrations
                     {
                         public const string V1TestEntityFinalizerIdentifier = "testing.dev/v1testentityfinalizer";
                         public static IOperatorBuilder RegisterFinalizers(this IOperatorBuilder builder)
                         {
                             builder.AddFinalizer<global::V1TestEntityFinalizer, global::V1TestEntityFromReferencedAssemblyInGlobalNamespace>(V1TestEntityFinalizerIdentifier);
                             return builder;
                         }
                     }
                     """,
        TestDisplayName = "Test finalizer with entity from referenced assembly in global namespace")]
    [InlineData(
        """
                using k8s;
                using k8s.Models;
                using KubeOps.Generator.Test.Entities;
                using KubeOps.Abstractions.Reconciliation.Finalizer;

                public abstract class EntityFinalizerBase<TEntity> : IEntityFinalizer<TEntity> 
                    where TEntity : IKubernetesObject<V1ObjectMeta>
                {
                }
                
                public sealed class V1TestEntityFinalizer : EntityFinalizerBase<V1TestEntityFromReferencedAssembly>
                {
                }
                """,
        """
                     // <auto-generated>
                     // This code was generated by a tool.
                     // Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
                     // </auto-generated>
                     #pragma warning disable CS1591
                     using KubeOps.Abstractions.Builder;

                     public static class FinalizerRegistrations
                     {
                         public const string V1TestEntityFinalizerIdentifier = "testing.dev/v1testentityfinalizer";
                         public static IOperatorBuilder RegisterFinalizers(this IOperatorBuilder builder)
                         {
                             builder.AddFinalizer<global::V1TestEntityFinalizer, global::KubeOps.Generator.Test.Entities.V1TestEntityFromReferencedAssembly>(V1TestEntityFinalizerIdentifier);
                             return builder;
                         }
                     }
                     """,
        TestDisplayName = "Test finalizer with inheritance and entity from referenced assembly")]
    [InlineData(
        """
                using KubeOps.Generator.Test.Entities;
                using KubeOps.Abstractions.Reconciliation.Finalizer;

                public partial class V1TestEntityFinalizer : IEntityFinalizer<V1TestEntityFromReferencedAssembly>
                {
                }

                public partial class V1TestEntityFinalizer : IEntityFinalizer<V1TestEntityFromReferencedAssembly>
                {
                }
                """,
        """
                     // <auto-generated>
                     // This code was generated by a tool.
                     // Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
                     // </auto-generated>
                     #pragma warning disable CS1591
                     using KubeOps.Abstractions.Builder;

                     public static class FinalizerRegistrations
                     {
                         public const string V1TestEntityFinalizerIdentifier = "testing.dev/v1testentityfinalizer";
                         public static IOperatorBuilder RegisterFinalizers(this IOperatorBuilder builder)
                         {
                             builder.AddFinalizer<global::V1TestEntityFinalizer, global::KubeOps.Generator.Test.Entities.V1TestEntityFromReferencedAssembly>(V1TestEntityFinalizerIdentifier);
                             return builder;
                         }
                     }
                     """,
        TestDisplayName = "Test partial finalizer with entity from referenced assembly")]
    [InlineData(
        """
                using KubeOps.Generator.Test.Entities;
                using KubeOps.Abstractions.Reconciliation.Finalizer;

                public sealed class V1TestEntityCleanupDeployment : IEntityFinalizer<V1TestEntityFromReferencedAssembly>
                {
                }

                public sealed class V1TestEntityCleanupOtherResourcesSuchThatThisFinalizerHasAVeryLongName : IEntityFinalizer<V1TestEntityFromReferencedAssembly>
                {
                }
                """,
        """
                     // <auto-generated>
                     // This code was generated by a tool.
                     // Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
                     // </auto-generated>
                     #pragma warning disable CS1591
                     using KubeOps.Abstractions.Builder;

                     public static class FinalizerRegistrations
                     {
                         public const string V1TestEntityCleanupDeploymentIdentifier = "testing.dev/v1testentitycleanupdeploymentfinalizer";
                         public const string V1TestEntityCleanupOtherResourcesSuchThatThisFinalizerHasAVeryLongNameIdentifier = "testing.dev/v1testentitycleanupotherresourcessuchthatthisfinali";
                         public static IOperatorBuilder RegisterFinalizers(this IOperatorBuilder builder)
                         {
                             builder.AddFinalizer<global::V1TestEntityCleanupDeployment, global::KubeOps.Generator.Test.Entities.V1TestEntityFromReferencedAssembly>(V1TestEntityCleanupDeploymentIdentifier);
                             builder.AddFinalizer<global::V1TestEntityCleanupOtherResourcesSuchThatThisFinalizerHasAVeryLongName, global::KubeOps.Generator.Test.Entities.V1TestEntityFromReferencedAssembly>(V1TestEntityCleanupOtherResourcesSuchThatThisFinalizerHasAVeryLongNameIdentifier);
                             return builder;
                         }
                     }
                     """,
        TestDisplayName = "Test multiple finalizers, one having an exceeding long name, with entity from referenced assembly")]
    [InlineData(
        """
                using KubeOps.Generator.Test.Entities;
                using KubeOps.Abstractions.Reconciliation.Finalizer;

                public abstract class EntityFinalizerBase<TEntity> : IEntityFinalizer<TEntity> 
                    where TEntity : IKubernetesObject<V1ObjectMeta>
                {
                }
                
                public sealed class V1TestEntityFinalizer : EntityFinalizerBase<V1TestEntityFromReferencedAssembly>
                {
                }

                public sealed class V1TestEntityFinalizer2 : IEntityFinalizer<V1TestEntityFromReferencedAssembly>
                {
                }
                """,
        """
                     // <auto-generated>
                     // This code was generated by a tool.
                     // Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
                     // </auto-generated>
                     #pragma warning disable CS1591
                     using KubeOps.Abstractions.Builder;

                     public static class FinalizerRegistrations
                     {
                         public const string V1TestEntityFinalizerIdentifier = "testing.dev/v1testentityfinalizer";
                         public const string V1TestEntityFinalizer2Identifier = "testing.dev/v1testentityfinalizer2finalizer";
                         public static IOperatorBuilder RegisterFinalizers(this IOperatorBuilder builder)
                         {
                             builder.AddFinalizer<global::V1TestEntityFinalizer, global::KubeOps.Generator.Test.Entities.V1TestEntityFromReferencedAssembly>(V1TestEntityFinalizerIdentifier);
                             builder.AddFinalizer<global::V1TestEntityFinalizer2, global::KubeOps.Generator.Test.Entities.V1TestEntityFromReferencedAssembly>(V1TestEntityFinalizer2Identifier);
                             return builder;
                         }
                     }
                     """,
        TestDisplayName = "Test multiple finalizers with inheritance and entity from referenced assembly")]
    [InlineData(
        """
                using k8s;
                using k8s.Models;
                using KubeOps.Generator.Test.Entities;
                using KubeOps.Abstractions.Reconciliation.Finalizer;

                [KubernetesEntity(Group = "testing.dev", ApiVersion = "v1", Kind = "TestEntity")]
                public class V1TestEntity : IKubernetesObject<V1ObjectMeta>
                {
                }
                
                public sealed class V1TestEntityFinalizer : IEntityFinalizer<V1TestEntity>
                {
                }

                public sealed class V1TestEntityFinalizer2 : IEntityFinalizer<KubeOps.Generator.Test.Entities.V1TestEntity>
                {
                }
                """,
        """
                     // <auto-generated>
                     // This code was generated by a tool.
                     // Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
                     // </auto-generated>
                     #pragma warning disable CS1591
                     using KubeOps.Abstractions.Builder;

                     public static class FinalizerRegistrations
                     {
                         public const string V1TestEntityFinalizerIdentifier = "testing.dev/v1testentityfinalizer";
                         public const string V1TestEntityFinalizer2Identifier = "testing.dev/v1testentityfinalizer2finalizer";
                         public static IOperatorBuilder RegisterFinalizers(this IOperatorBuilder builder)
                         {
                             builder.AddFinalizer<global::V1TestEntityFinalizer, global::V1TestEntity>(V1TestEntityFinalizerIdentifier);
                             builder.AddFinalizer<global::V1TestEntityFinalizer2, global::KubeOps.Generator.Test.Entities.V1TestEntity>(V1TestEntityFinalizer2Identifier);
                             return builder;
                         }
                     }
                     """,
        TestDisplayName = "Test multiple finalizers with inheritance and one entity from referenced assembly and one defined locally")]
    public void Should_Generate_Correct_Code_FromReferencedAssembly(string input, string expectedResult)
    {
        var inputCompilation = input.CreateCompilation(
            additionalReferences: MetadataReference
                .CreateFromFile(typeof(V1TestEntityFromReferencedAssembly)
                    .GetTypeInfo().Assembly.Location));
        expectedResult = expectedResult.ReplaceLineEndings();

        var driver = CSharpGeneratorDriver.Create(new FinalizerRegistrationGenerator());
        driver.RunGeneratorsAndUpdateCompilation(
            inputCompilation,
            out var output,
            out ImmutableArray<Diagnostic> _,
            TestContext.Current.CancellationToken);

        var result = output.SyntaxTrees
            .First(s => s.FilePath.Contains("FinalizerRegistrations.g.cs"))
            .ToString().ReplaceLineEndings();
        result.Should().Be(expectedResult);
    }
}
