// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.

using System.Text;

using KubeOps.Generator.SyntaxReceiver;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace KubeOps.Generator.Generators;

[Generator]
internal sealed class EntityInitializerGenerator : ISourceGenerator
{
    private const string EntityIdentifier = "entity";

    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new KubernetesEntitySyntaxReceiver());
    }

    public void Execute(GeneratorExecutionContext context)
    {
        if (context.SyntaxContextReceiver is not KubernetesEntitySyntaxReceiver receiver)
        {
            return;
        }

        // for each partial defined entity, create a partial class that
        // introduces a default constructor that initializes the ApiVersion and Kind.
        // But only, if there is no default constructor defined.
        foreach (var entity in receiver.Entities.Where(e => e.ClassDeclaration is { IsFromReferencedAssembly: false, IsPartial: true, HasParameterlessConstructor: false }))
        {
            var ns = new List<MemberDeclarationSyntax>();
            if (!string.IsNullOrEmpty(entity.ClassDeclaration.Namespace))
            {
                ns.Add(FileScopedNamespaceDeclaration(IdentifierName(entity.ClassDeclaration.Namespace!)));
            }

            var partialEntityInitializer = CompilationUnit();

            if (ns.Count > 0)
            {
                partialEntityInitializer = partialEntityInitializer
                    .AddMembers(ns.ToArray())
                    .WithLeadingTrivia(AutoGeneratedSyntaxTrivia.Instance);
            }

            partialEntityInitializer = partialEntityInitializer
                .AddMembers(ClassDeclaration(entity.ClassDeclaration.ClassName)
                    .WithModifiers(entity.ClassDeclaration.Modifiers!.Value)
                    .AddMembers(ConstructorDeclaration(entity.ClassDeclaration.ClassName)
                        .WithModifiers(
                            TokenList(
                                Token(SyntaxKind.PublicKeyword)))
                        .WithBody(
                            Block(
                                ExpressionStatement(
                                    AssignmentExpression(
                                        SyntaxKind.SimpleAssignmentExpression,
                                        IdentifierName("ApiVersion"),
                                        LiteralExpression(
                                            SyntaxKind.StringLiteralExpression,
                                            Literal($"{entity.Group}/{entity.Version}".TrimStart('/'))))),
                                ExpressionStatement(
                                    AssignmentExpression(
                                        SyntaxKind.SimpleAssignmentExpression,
                                        IdentifierName("Kind"),
                                        LiteralExpression(
                                            SyntaxKind.StringLiteralExpression,
                                            Literal(entity.Kind))))))));

            if (ns.Count == 0)
            {
                partialEntityInitializer = partialEntityInitializer
                    .WithLeadingTrivia(AutoGeneratedSyntaxTrivia.Instance);
            }

            partialEntityInitializer = partialEntityInitializer
                .NormalizeWhitespace();

            context.AddSource(
                $"{entity.ClassDeclaration.ClassName}.init.g.cs",
                SourceText.From(partialEntityInitializer.ToFullString(), Encoding.UTF8, SourceHashAlgorithm.Sha256));
        }

        // for each NON partial entity or referenced by assembly,
        // generate a method extension that initializes the ApiVersion and Kind.
        var staticInitializers = CompilationUnit()
            .WithMembers(SingletonList<MemberDeclarationSyntax>(ClassDeclaration("EntityInitializer")
                .WithModifiers(TokenList(
                    Token(SyntaxKind.PublicKeyword), Token(SyntaxKind.StaticKeyword)))
                .WithMembers(List<MemberDeclarationSyntax>(receiver.Entities
                    .Where(e => e.ClassDeclaration.IsFromReferencedAssembly || !e.ClassDeclaration.IsPartial || e.ClassDeclaration.HasParameterlessConstructor)
                    .Select(e => (Entity: e, ClassIdentifier: e.ClassDeclaration.FullyQualifiedName))
                    .Select(e => MethodDeclaration(
                            IdentifierName(e.ClassIdentifier),
                            "Initialize")
                        .WithModifiers(
                            TokenList(Token(SyntaxKind.PublicKeyword), Token(SyntaxKind.StaticKeyword)))
                        .WithParameterList(ParameterList(
                            SingletonSeparatedList(
                                Parameter(
                                        Identifier(EntityIdentifier))
                                    .WithModifiers(
                                        TokenList(
                                            Token(SyntaxKind.ThisKeyword)))
                                    .WithType(IdentifierName(e.ClassIdentifier)))))
                        .WithBody(Block(
                            ExpressionStatement(
                                AssignmentExpression(
                                    SyntaxKind.SimpleAssignmentExpression,
                                    MemberAccessExpression(
                                        SyntaxKind.SimpleMemberAccessExpression,
                                        IdentifierName(EntityIdentifier),
                                        IdentifierName("ApiVersion")),
                                    LiteralExpression(
                                        SyntaxKind.StringLiteralExpression,
                                        Literal($"{e.Entity.Group}/{e.Entity.Version}".TrimStart('/'))))),
                            ExpressionStatement(
                                AssignmentExpression(
                                    SyntaxKind.SimpleAssignmentExpression,
                                    MemberAccessExpression(
                                        SyntaxKind.SimpleMemberAccessExpression,
                                        IdentifierName(EntityIdentifier),
                                        IdentifierName("Kind")),
                                    LiteralExpression(
                                        SyntaxKind.StringLiteralExpression,
                                        Literal(e.Entity.Kind)))),
                            ReturnStatement(IdentifierName(EntityIdentifier)))))))))
            .WithLeadingTrivia(AutoGeneratedSyntaxTrivia.Instance)
            .NormalizeWhitespace();

        context.AddSource(
            "EntityInitializer.g.cs",
            SourceText.From(staticInitializers.ToFullString(), Encoding.UTF8, SourceHashAlgorithm.Sha256));
    }
}
